apiVersion: apps/v1
kind: Deployment
metadata:
  name: aplay-client
  namespace: aplay
spec:
  replicas: 2
  selector:
    matchLabels:
      run: aplay-client
  template:
    metadata:
      labels:
        run: aplay-client
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
      - image: docker.io/coreight98/aplay-client:main
        name: aplay-client
        ports:
        - containerPort: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: aplay-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      run: aplay-backend
  template:
    metadata:
      labels:
        run: aplay-backend
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
      - image: docker.io/minshigee/aplay-backend:202211020329
        name: aplay-backend
        ports:
        - containerPort: 8080
