apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: aplay
spec:
  selector:
    app.kubernetes.io/app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306

---

apiVersion: apps/v1
kind: Pod
metadata:
  name: mysql
  namespace: aplay
spec:
  selector:
    app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
        - name: mysql
          image: mysql:8.0.26
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-root
                  key: password
          ports:
            - containerPort: 3306