apiVersion: v1
kind: Service
metadata:
  name: headless-to-aplay-client
  namespace: default
spec:
  type: ExternalName
  externalName: aplay-client-loadbalancer.aplay.svc.cluster.local
  ports:
    - port: 443
      targetPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: aplay-client-loadbalancer
  namespace: aplay
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: aplay-client

---

apiVersion: v1
kind: Service
metadata:
  name: aplay-backend-loadbalancer
  namespace: aplay
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    run: aplay-backend
