apiVersion: apps/v1
kind: Deployment
metadata:
  name: aplay-client
  namespace: aplay
spec:
  replicas: 2
  selector:
    matchLabels:
      run: aplay-client
  template:
    metadata:
      labels:
        run: aplay-client
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
      - image: docker.io/minshigee/aplay-client:tempmain1
        name: aplay-client
        ports:
        - containerPort: 80
