apiVersion: v1
kind: Service
metadata:
  name: aplay-express-loadbalancer
  namespace: aplay
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: 4000
  externalIPs:
    - 152.67.200.167
  selector:
    run: aplay-express
