apiVersion: apps/v1 #beta2 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: kms-deployment
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: kms
  replicas: 1 # tells deployment to run 1 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: kms
    spec:
      containers:
        - name: kms
          image: kurento/kurento-media-server:6.7.1-xenial
          env:
            - name: "KMS_TURN_URL"
              value: "aplay:root1234!@35.157.143.31:3478"
          ports:
            - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: kms-service
  labels:
    app: kms
spec:
  type: NodePort
  ports:
    - port: 8888
      targetPort: 8888
      protocol: TCP
  selector:
    app: kms
    
---

apiVersion: v1
kind: Service
metadata:
  name: headless-to-kms-service
  namespace: default
spec:
  type: ExternalName
  externalName: kms-service.aplay.svc.cluster.local
  ports:
    - port: 443
      targetPort: 8888
