apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/issuer: "letsencrypt-prod"

  name: rules-ingress
  namespace: default
spec:
  ingressClassName: nginx
  tls:
  - hosts:
      - www.aplay.n-e.kr
    secretName: tls-ingress

  rules:
    - host: "www.aplay.n-e.kr"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: my-nginx
                port:
                  number: 80

    - host: "argocd.aplay.n-e.kr"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: argocd-server
                port:
                  number: 443