apiVersion: v1
kind: Secret
metadata:
  namespace: aplay
  name: mysql-root
type: Opaque
data:
  password:

---

apiVersion: v1
kind: Secret
metadata:
  namespace: aplay
  name: redis-secrets
type: Opaque
data:
  password:

